
package view.Relatorio;

import apoio.ConexaoBD;
import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author gabri
 */
public class jif_relatorio extends javax.swing.JPanel {
    HashMap<String, String> reports;
    private String basePath = "/view/Relatorio/";

    /**
     * Creates new form jiif_relatorio
     */
    public jif_relatorio() {
        this.reports = new HashMap();
        reports.put("Compras por Item", basePath + "RelCompras.jrxml");
        reports.put("Vendas por Item", basePath + "RelVendas.jrxml");
        reports.put("Produção por Item", basePath + "RelProducao.jrxml");
        reports.put("Lucro do Período", basePath + "RelLucro.jrxml");

        
        MaskFormatter dateMask1;
        MaskFormatter dateMask2;
        try {
            dateMask1 = new MaskFormatter("##/##/####");
            dateMask2 = new MaskFormatter("##/##/####");
        } catch (Exception e) {
            dateMask1 = null;
            dateMask2 = null;
        }
                
        initComponents();
        dateMask1.install(dataInicio);
        dateMask2.install(dataFim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reportSelector = new javax.swing.JComboBox<>();
        reportRun = new javax.swing.JButton();
        paneParameters = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dataInicio = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        dataFim = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(238, 238, 238));
        setForeground(new java.awt.Color(0, 0, 0));
        setLayout(new java.awt.BorderLayout());

        reportSelector.setBackground(new java.awt.Color(238, 238, 238));
        reportSelector.setForeground(new java.awt.Color(0, 0, 0));
        reportSelector.setModel(new javax.swing.DefaultComboBoxModel<Object>(this.reports.keySet().toArray()));
        reportSelector.setMinimumSize(new java.awt.Dimension(300, 50));
        reportSelector.setPreferredSize(new java.awt.Dimension(300, 50));
        reportSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportSelectorActionPerformed(evt);
            }
        });
        add(reportSelector, java.awt.BorderLayout.PAGE_START);

        reportRun.setBackground(new java.awt.Color(13, 71, 161));
        reportRun.setForeground(new java.awt.Color(255, 255, 255));
        reportRun.setText("Gerar");
        reportRun.setMaximumSize(new java.awt.Dimension(72, 50));
        reportRun.setMinimumSize(new java.awt.Dimension(72, 50));
        reportRun.setPreferredSize(new java.awt.Dimension(72, 50));
        reportRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportRunActionPerformed(evt);
            }
        });
        add(reportRun, java.awt.BorderLayout.PAGE_END);

        paneParameters.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel1.setLayout(new java.awt.GridLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("De");
        jPanel1.add(jLabel1);

        dataInicio.setBackground(new java.awt.Color(238, 238, 238));
        dataInicio.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(dataInicio);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Até");
        jPanel1.add(jLabel2);

        dataFim.setBackground(new java.awt.Color(238, 238, 238));
        jPanel1.add(dataFim);

        paneParameters.add(jPanel1);

        add(paneParameters, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void reportSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportSelectorActionPerformed

    private void reportRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportRunActionPerformed
        try {
            String selectedReport = reports.get((String) reportSelector.getSelectedItem());
            InputStream inputStream = getClass().getResourceAsStream(selectedReport);
            JasperReport report = JasperCompileManager.compileReport(inputStream);
            
            Map params = new HashMap<>();
            params.put("dataIni", dataInicio.getText());
            params.put("dataFim", dataFim.getText());
            
            JasperPrint print = JasperFillManager.fillReport(
                    report, 
                    params, 
                    ConexaoBD.getInstance().getConnection()
            );
            
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            Logger.getLogger(jif_relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reportRunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dataFim;
    private javax.swing.JFormattedTextField dataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel paneParameters;
    private javax.swing.JButton reportRun;
    private javax.swing.JComboBox<Object> reportSelector;
    // End of variables declaration//GEN-END:variables
}
