
package view.Relatorio;

/**
 *
 * @author gabri
 */
public class jif_relatorio extends javax.swing.JPanel {

    /**
     * Creates new form jiif_relatorio
     */
    public jif_relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_relatiorio = new javax.swing.JTable();
        jbt_estrutura = new javax.swing.JButton();
        jbt_item = new javax.swing.JButton();
        jbt_grupo1 = new javax.swing.JButton();
        jbt_estoque = new javax.swing.JButton();
        jbt_cliente = new javax.swing.JButton();
        jbt_fornecedor = new javax.swing.JButton();
        jbt_usuario = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 238, 238));
        setForeground(new java.awt.Color(0, 0, 0));

        jtb_relatiorio.setBackground(new java.awt.Color(250, 250, 250));
        jtb_relatiorio.setForeground(new java.awt.Color(51, 51, 51));
        jtb_relatiorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtb_relatiorio.setRowHeight(25);
        jtb_relatiorio.setSelectionBackground(new java.awt.Color(13, 71, 161));
        jtb_relatiorio.setSelectionForeground(new java.awt.Color(250, 250, 250));
        jtb_relatiorio.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtb_relatiorio.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(jtb_relatiorio);

        jbt_estrutura.setBackground(new java.awt.Color(13, 71, 161));
        jbt_estrutura.setForeground(new java.awt.Color(255, 255, 255));
        jbt_estrutura.setText("ESTRUTURA");
        jbt_estrutura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_estruturaActionPerformed(evt);
            }
        });

        jbt_item.setBackground(new java.awt.Color(13, 71, 161));
        jbt_item.setForeground(new java.awt.Color(255, 255, 255));
        jbt_item.setText("ITEM");
        jbt_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_itemActionPerformed(evt);
            }
        });

        jbt_grupo1.setBackground(new java.awt.Color(13, 71, 161));
        jbt_grupo1.setForeground(new java.awt.Color(255, 255, 255));
        jbt_grupo1.setText("GRUPO");
        jbt_grupo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_grupo1ActionPerformed(evt);
            }
        });

        jbt_estoque.setBackground(new java.awt.Color(13, 71, 161));
        jbt_estoque.setForeground(new java.awt.Color(255, 255, 255));
        jbt_estoque.setText("ESTOQUE");
        jbt_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_estoqueActionPerformed(evt);
            }
        });

        jbt_cliente.setBackground(new java.awt.Color(13, 71, 161));
        jbt_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jbt_cliente.setText("CLIENTE");
        jbt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_clienteActionPerformed(evt);
            }
        });

        jbt_fornecedor.setBackground(new java.awt.Color(13, 71, 161));
        jbt_fornecedor.setForeground(new java.awt.Color(255, 255, 255));
        jbt_fornecedor.setText("FORNECEDOR");

        jbt_usuario.setBackground(new java.awt.Color(13, 71, 161));
        jbt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        jbt_usuario.setText("USUARIO");
        jbt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_usuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jbt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbt_grupo1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbt_estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbt_fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbt_item, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbt_estrutura, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_fornecedor)
                    .addComponent(jbt_item)
                    .addComponent(jbt_estrutura)
                    .addComponent(jbt_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_estoque)
                    .addComponent(jbt_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_grupo1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_estruturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_estruturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_estruturaActionPerformed

    private void jbt_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_itemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_itemActionPerformed

    private void jbt_grupo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_grupo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_grupo1ActionPerformed

    private void jbt_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_estoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_estoqueActionPerformed

    private void jbt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_clienteActionPerformed

    private void jbt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_usuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_cliente;
    private javax.swing.JButton jbt_estoque;
    private javax.swing.JButton jbt_estrutura;
    private javax.swing.JButton jbt_fornecedor;
    private javax.swing.JButton jbt_grupo1;
    private javax.swing.JButton jbt_item;
    private javax.swing.JButton jbt_usuario;
    private javax.swing.JTable jtb_relatiorio;
    // End of variables declaration//GEN-END:variables
}
